=== knsathya/kernel-libs/klibs/schemas/release-schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "description": "Kernel release schema",
    "type": "object",
    "properties": {
        "bundle": {
            "type": "object",
            "properties": {
                "enable": {
                    "description": "Enable this option if you want to create git bundle.",
                    "type": "boolean",
                    "default": false
                },
                "mode": {
                    "description": "Bundle Mode",
                    "enum": [
                        "branch",
                        "diff",
                        "commit_count"
                    ],
                    "default": "branch"
                },
                "branch": {
                    "description": "Name of the kernel branch",
                    "type": "string",
                    "default": ""
                },
                "base": {
                    "type": "object",
                    "properties": {
                        "auto": {
                            "type": "boolean",
                            "default": true
                        },
                        "grep_tag": {
                            "type": "string",
                            "default": "Linux "
                        },
                        "value": {
                            "type": "string",
                            "default": "HEAD"
                        }
                    }
                },
                "head": {
                    "type": "object",
                    "properties": {
                        "auto": {
                            "type": "boolean",
                            "default": true
                        },
                        "grep_tag": {
                            "type": "string",
                            "default": "Linux "
                        },
                        "value": {
                            "type": "string",
                            "default": "HEAD"
                        }
                    }
                },
                "commit_count": {
                    "type": "number",
                    "default": 0
                },
                "outname": {
                    "type": "string",
                    "default": "Linux.bundle"
                },
                "upload-dir": {
                    "type": "string",
                    "default": ""
                },
                "upload-params": {
                    "$ref": "#/definitions/upload-params"
                }
            }
        },
        "quilt": {
            "type": "object",
            "properties": {
                "enable": {
                    "description": "Enable this option if you want to create git bundle.",
                    "type": "boolean",
                    "default": false
                },
                "branch": {
                    "description": "Name of the kernel branch",
                    "type": "string",
                    "default": ""
                },
                "base": {
                    "type": "object",
                    "properties": {
                        "auto": {
                            "type": "boolean",
                            "default": true
                        },
                        "grep_tag": {
                            "type": "string",
                            "default": "Linux "
                        },
                        "value": {
                            "type": "string",
                            "default": "HEAD"
                        }
                    }
                },
                "head": {
                    "type": "object",
                    "properties": {
                        "auto": {
                            "type": "boolean",
                            "default": true
                        },
                        "grep_tag": {
                            "type": "string",
                            "default": "Linux "
                        },
                        "value": {
                            "type": "string",
                            "default": "HEAD"
                        }
                    }
                },
                "sed-file": {
                    "type": "string",
                    "default": ""
                },
                "series-comment": {
                    "type": "string",
                    "default": ""
                },
                "audit-script": {
                    "type": "string",
                    "default": ""
                },
                "outname": {
                    "type": "string",
                    "default": "quilt"
                },
                "upload-dir": {
                    "type": "string",
                    "default": ""
                },
                "upload-params": {
                    "$ref": "#/definitions/upload-params"
                }
            }
        },
        "tar": {
            "type": "object",
            "properties": {
                "enable": {
                    "description": "Enable this option if you want to create tar file.",
                    "type": "boolean",
                    "default": false
                },
                "outname": {
                    "type": "string",
                    "default": "Linux.tar"
                },
                "skip-files": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "default": [".git"]
                },
                "upload-dir": {
                    "type": "string",
                    "default": ""
                },
                "upload-params": {
                    "$ref": "#/definitions/upload-params"
                }
            }
        },
        "upload-kernel": {
            "type": "object",
            "properties": {
                "enable": {
                    "description": "Enable this option if you want to upload kernel.",
                    "type": "boolean",
                    "default": false
                },
                "upload-dir": {
                    "type": "string",
                    "default": ""
                },
                "upload-params": {
                    "$ref": "#/definitions/upload-params"
                }
            }
        }
    },
    "definitions": {
        "upload-params": {
            "type": "object",
            "required": ["remote-list"],
            "properties": {
                "enable": {
                    "type": "boolean",
                    "description": "Enable if you want to upload"
                },
                "remote-list": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": ["name", "url"],
                        "properties": {
                            "name": {
                                "type": "string",
                                "description": "remote name"
                            },
                            "url": {
                                "type": "string",
                                "description": "remote URL"
                            },
                            "path": {
                                "type": "string",
                                "description": "remote relative directory",
                                "default": ""
                            },
                            "branch": {
                                "type": "string",
                                "description": "remote branch name",
                                "default": "master"
                            }
                        }
                    }
                },
                "use-refs": {
                    "type": "boolean",
                    "default": false
                },
                "force-push": {
                    "type": "boolean",
                    "default": false
                },
                "clean-update": {
                    "type": "boolean",
                    "default": false
                },
                "new-commit": {
                    "type": "boolean",
                    "default": false
                },
                "copy-formats": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "default": ["*"]
                },
                "commit-msg": {
                    "type": "string"
                },
                "timestamp-suffix": {
                    "type": "boolean",
                    "description": "Enable if you want to add timestamp suffix to remote directory.",
                    "default": false
                },
                "timestamp-format":{
                    "type": "string",
                    "description": "Timestamp format",
                    "default": "%m%d%Y%H%M%S"
                },
                "suffix-sep": {
                    "type": "string",
                    "description": "Suffix seperator",
                    "default": "-"
                },
                "tag-list": {
                    "type": "array",
                    "items": {
                        "properties": {
                            "name": {
                                "type": "string",
                                "description": "Name of the tag"
                            },
                            "msg": {
                                "type": "string",
                                "description": ""
                            }
                        }
                    }
                }
            }
        }
    }
}

=== knsathya/kernel-libs/tests/config/release-config.json
{
    "quilt": {
        "enable": false,
        "outname": "quilt",
        "sed-file": "",
        "series-comment": "",
        "audit-script": "",
        "branch": "",
        "base": {
            "auto": false,
            "grep_tag": "Linux ",
            "value": "HEAD"
        },
        "head": {
            "auto": false,
            "grep_tag": "Linux ",
            "value": "HEAD"
        },
        "upload-params": {
            "enable": false,
            "remote-list": [
                {
                    "name": "origin",
                    "url": "https://knsathya@github.com/knsathya/linux.git",
                    "path": ".",
                    "branch": "master"
                }
            ],
            "new-commit": false,
            "commit-msg": "",
            "tag-list": []
        }
    },
    "bundle": {
        "enable": false,
        "outname": "Linux 4.18-rc3.bundle",
        "mode": "branch",
        "commit_count": 0,
        "branch": "",
        "base": {
            "auto": false,
            "grep_tag": "Linux ",
            "value": "HEAD"
        },
        "head": {
            "auto": false,
            "grep_tag": "Linux ",
            "value": "HEAD"
        },
        "upload-params": {
            "enable": false,
            "remote-list": [
                {
                    "name": "origin",
                    "url": "https://knsathya@github.com/knsathya/linux.git",
                    "path": ".",
                    "branch": "master"
                }
            ],
            "new-commit": false,
            "commit-msg": "",
            "tag-list": []
        }
    },
    "tar": {
        "enable": false,
        "outname": "Linux 4.18-rc3.bundle",
        "upload-params": {
            "enable": false,
            "remote-list": [
                {
                    "name": "origin",
                    "url": "https://knsathya@github.com/knsathya/linux.git",
                    "path": ".",
                    "branch": "master"
                }
            ],
            "new-commit": false,
            "commit-msg": "",
            "tag-list": []
        }
    },
    "upload-kernel": {
        "enable": false,
        "upload-params": {
            "enable": false,
            "remote-list": [
                {
                    "name": "origin",
                    "url": "https://knsathya@github.com/knsathya/linux.git",
                    "path": ".",
                    "branch": "master"
                }
            ],
            "new-commit": false,
            "commit-msg": "",
            "tag-list": []
        }
    }
}
